name: BasicBroadcast
version: 1.0.0
author: Romejanic
api-version: 1.15

main: com.romejanic.bb.BasicBroadcast

commands:
    bb:
        description: Base command for BasicBroadcast
        usage: /bb ...