name: BasicBroadcast
version: 1.0.2
author: Romejanic
api-version: 1.15

main: com.romejanic.bb.BasicBroadcast

commands:
    bb:
        description: Base command for BasicBroadcast
        usage: /bb <list|reload|version|changes>
        aliases: basicbroadcast